"""
metadata.py

Create metadata.json describing the execution environment,
configuration, datasets and generated outputs.

Author: Marlon Souza et al.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------

def _git(command: list[str]) -> str | None:
    """Execute a git command and return its output."""

    try:
        return subprocess.check_output(
            command,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return None


def _count_files(folder: Path, pattern: str) -> int:
    if not folder.exists():
        return 0
    return len(list(folder.rglob(pattern)))


def _list_relative(folder: Path):
    if not folder.exists():
        return []

    files = []

    for f in folder.rglob("*"):
        if f.is_file():
            files.append(str(f.relative_to(folder)))

    return sorted(files)


def _sha256(filename: Path) -> str:
    """
    Compute SHA256 of a file.

    Used only for important output files.
    """

    h = hashlib.sha256()

    with open(filename, "rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)

    return h.hexdigest()


# ---------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------

def write_metadata(
    *,
    output_file: Path,
    paths: dict,
    config: dict,
    runtime_seconds: float,
    execution_summary: dict | None = None,
):
    """
    Write metadata.json.

    Parameters
    ----------
    output_file
        metadata.json location.

    paths
        Dictionary returned by setup_paths().

    config
        Configuration dictionary.

    runtime_seconds
        Total execution time.

    execution_summary
        Optional dictionary generated by run.py containing
        information such as models executed, experiments,
        skipped experiments, etc.
    """

    output_file.parent.mkdir(parents=True, exist_ok=True)

    metadata = {}

    # -------------------------------------------------------------
    # Timestamp
    # -------------------------------------------------------------

    metadata["execution"] = {
        "date": datetime.now().isoformat(timespec="seconds"),
        "runtime_seconds": round(runtime_seconds, 2),
    }

    # -------------------------------------------------------------
    # Platform
    # -------------------------------------------------------------

    metadata["platform"] = {
        "python": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "system": platform.system(),
        "release": platform.release(),
        "machine": platform.machine(),
        "processor": platform.processor(),
        "executable": sys.executable,
    }

    # -------------------------------------------------------------
    # Git
    # -------------------------------------------------------------

    metadata["git"] = {
        "commit": _git(["git", "rev-parse", "HEAD"]),
        "branch": _git(["git", "rev-parse", "--abbrev-ref", "HEAD"]),
        "tag": _git(["git", "describe", "--tags"]),
    }

    # -------------------------------------------------------------
    # Configuration
    # -------------------------------------------------------------

    metadata["configuration"] = config

    # -------------------------------------------------------------
    # Datasets
    # -------------------------------------------------------------

    datasets = {}

    if "S2_imagery" in paths:
        datasets["Sentinel2_images"] = _count_files(
            Path(paths["S2_imagery"]),
            "*.tif",
        )

    if "PS_imagery" in paths:
        datasets["PlanetScope_images"] = _count_files(
            Path(paths["PS_imagery"]),
            "*.tif",
        )

    if "datasets_path" in paths:

        datasets["CSV_files"] = _count_files(
            Path(paths["datasets_path"]),
            "*.csv",
        )

    metadata["datasets"] = datasets

    # -------------------------------------------------------------
    # Results
    # -------------------------------------------------------------

    results = {}

    results_path = Path(paths["results_path"])

    results["excel_files"] = _list_relative(results_path)

    if "figures_path" in paths:

        results["figures"] = _list_relative(
            Path(paths["figures_path"])
        )

    if "maps_path" in paths:

        results["maps"] = _list_relative(
            Path(paths["maps_path"])
        )

    metadata["results"] = results

    # -------------------------------------------------------------
    # Checksums
    # -------------------------------------------------------------

    checksums = {}

    for excel in results_path.glob("*.xlsx"):
        checksums[excel.name] = _sha256(excel)

    metadata["checksums"] = checksums

    # -------------------------------------------------------------
    # Optional execution summary
    # -------------------------------------------------------------

    if execution_summary is not None:
        metadata["execution_summary"] = execution_summary

    # -------------------------------------------------------------
    # Environment variables
    # -------------------------------------------------------------

    metadata["environment"] = {
        "CODEOCEAN": os.getenv("CODEOCEAN", ""),
        "PYTHONHASHSEED": os.getenv("PYTHONHASHSEED", ""),
    }

    # -------------------------------------------------------------
    # Save
    # -------------------------------------------------------------

    with open(output_file, "w", encoding="utf8") as f:
        json.dump(
            metadata,
            f,
            indent=4,
            ensure_ascii=False,
        )

    print(f"\nMetadata written to:\n{output_file}")