# hash:sha256:d023e8a2183e2b103f42c20e9c64e951eb308e67c24a23b30814f761dd07c01a
FROM registry.codeocean.com/codeocean/py-r:python3.12.8-R4.4.2-JupyterLab4.3.5-RStudiorstudio-server-2024.12.1-563-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    gcc==latest
